//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;


namespace ASF.Business
{
    /// <summary>
    /// CategoryBusiness business component.
    /// </summary>
    public class CategoryBusiness
    {
        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="category"></param>
        /// <returns></returns>
        public Category Add(Category category)
        {
            var categoryDac = new CategoryDac();
            return categoryDac.Create(category);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var categoryDac = new CategoryDac();
            categoryDac.DeleteById(id);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public List<Category> All()
        {
            var categoryDac = new CategoryDac();
            var result = categoryDac.Select();
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Category Find(int id)
        {
            var categoryDac = new CategoryDac();
            var result = categoryDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// 
        /// </summary>
        /// <param name="category"></param>
        public void Edit(Category category)
        {
            var categoryDac = new CategoryDac();
            categoryDac.UpdateById(category);
        }
    }
}
