//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    /// <summary>
    /// CountryBusiness business component.
    /// </summary>
    public class CountryBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="country"></param>
        /// <returns></returns>
        public Country Add(Country country)
        {
            var countryDac = new CountryDAC();
            return countryDac.Create(country);
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var countryDac = new CountryDAC();
            countryDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<Country> All()
        {
            var countryDac = new CountryDAC();
            var result = countryDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Country Find(int id)
        {
            var countryDac = new CountryDAC();
            var result = countryDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="country"></param>
        public void Edit(Country country)
        {
            var countryDac = new CountryDAC();
            countryDac.UpdateById(country);
        }

    }
}
