//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    /// <summary>
    /// OrderNumberBusiness business component.
    /// </summary>
    public class OrderNumberBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="orderNumber"></param>
        /// <returns></returns>
        public OrderNumber Add(OrderNumber orderNumber)
        {
            var orderNumberDac = new OrderNumberDAC();
            return orderNumberDac.Create(orderNumber);
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var orderNumberDac = new OrderNumberDAC();
            orderNumberDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<OrderNumber> All()
        {
            var orderNumberDac = new OrderNumberDAC();
            var result = orderNumberDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public OrderNumber Find(int id)
        {
            var orderNumberDac = new OrderNumberDAC();
            var result = orderNumberDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="orderNumber"></param>
        public void Edit(OrderNumber orderNumber)
        {
            var orderNumberDac = new OrderNumberDAC();
            orderNumberDac.UpdateById(orderNumber);
        }

    }
}
