//====================================================================================================
// Base code generated with LeatherGoods - ASF.Business
// Architecture Solutions Foundation
//
// Generated by academic at LeatherGoods V 1.0 
//====================================================================================================

using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using ASF.Entities;
using ASF.Data;

namespace ASF.Business
{
    /// <summary>
    /// RatingBusiness business component.
    /// </summary>
    public class RatingBusiness
    {

        /// <summary>
        /// Add method. 
        /// </summary>
        /// <param name="rating"></param>
        /// <returns></returns>
        public Rating Add(Rating rating)
        {
            var ratingDac = new RatingDAC();
            return ratingDac.Create(rating);
        }

        /// <summary>
        /// Delete method.
        /// </summary>
        /// <param name="id"></param>
        public void Remove(int id)
        {
            var ratingDac = new RatingDAC();
            ratingDac.DeleteById(id);
        }

        /// <summary>
        /// FindAll method.
        /// </summary>
        /// <returns></returns>
        public List<Rating> All()
        {
            var ratingDac = new RatingDAC();
            var result = ratingDac.Select();
            return result;
        }

        /// <summary>
        /// Find method.
        /// </summary>
        /// <param name="id"></param>
        /// <returns></returns>
        public Rating Find(int id)
        {
            var ratingDac = new RatingDAC();
            var result = ratingDac.SelectById(id);
            return result;
        }

        /// <summary>
        /// Update method.
        /// </summary>
        /// <param name="rating"></param>
        public void Edit(Rating rating)
        {
            var ratingDac = new RatingDAC();
            ratingDac.UpdateById(rating);
        }

    }
}
